# Generated by Django 4.0.5 on 2022-06-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
