# Generated by Django 4.0.4 on 2022-06-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
